services:
  ms-game-db:
    image: "postgres:latest"
    container_name: game-db
    ports:
      - "5434:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - src/main/resources/environment/.env
    volumes:
      - ms_game_data:/var/lib/postgresql/data

  ms-user-db:
    image: "postgres:latest"
    container_name: user-db
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - src/main/resources/environment/ms_user.env
    volumes:
      - ms_user_data:/var/lib/postgresql/data

  eureka:
    image: service-registry-main
    container_name: host-eureka
    ports:
      - "8761:8761"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  gateway:
    image: api-gateway-main
    container_name: host-gateway
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - src/main/resources/environment/docker.env
    depends_on:
      - eureka

  redis:
    image: "redis:latest"
    container_name: host-redis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    ports:
      - "6379:6379"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - src/main/resources/environment/docker.env

  postgres-keycloak:
    image: postgres:latest
    container_name: keycloak-postgres
    env_file:
      - src/main/resources/environment/keycloak.env
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: host-keycloak
    env_file:
      - src/main/resources/environment/keycloak.env
    command:
      [ "start-dev", "--http-port=9000", "--https-port=9000" ]
    ports:
      - "9000:9000"
    depends_on:
      - postgres-keycloak

volumes:
  ms_game_data:
  ms_user_data:
  keycloak_data: