spring:
  application:
    name: "ms-game"
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: ${TOKEN_URI}
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri: ${JWK_SET_URI}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8082